### PR TITLE
Mccgrey

### PR DESCRIPTION
**Pull request by MccGrey**
## update on all tasks

### CODE REVIEW

**Review by DanSam5K — CHANGES_REQUESTED** [review]
## Hi @MccGrey, 

Good job so far! you have really done a wonderful job 🥇 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!
### Required Changes ♻️
- Check the video demonstration and fix the changes if you understand 
https://www.loom.com/share/5f38a7b6ff904cb0aa741a8bc807e0c3

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by MccGrey** [comment]
alright boss, I'm on it!!! ✌✌

**Comment by MccGrey** [comment]
I just made the changes, please check and reach out boss. 🙌🙌🙌

**Review by DanSam5K — APPROVED** [review]
### Hi @MccGrey , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by MccGrey** [comment]
😎✌!!!

**Pull request merged**
