### PR TITLE
using scss/sass

### PR DESCRIPTION
**Pull request by Emmanuel-obiora**
Learning SCSS/SASS in writing styles for web pages.

### CODE REVIEW

**Review by DanSam5K — CHANGES_REQUESTED** [review]
## Hi @Emmanuel-obiora , 

Good job so far!
✔️ You went extra miles to create an interactive UI for the project good Job 🤝 .
✔️ Good Job with using JQuery and more JS functionality to create a good user experience.

There are some issues that you still need to work on to go to the next project but you are almost there!
### You can also consider:
- [ ] Removing the empty files in this project and commit the changes to your work. or implement the solution intended for creating the files. It will help give a professional feel to the project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Emmanuel-obiora** [comment]
The empty files are for the 1st assignment. Full name display and am currently working on it. Or should I just delete the files  and re-update pending the completion of the lass assignment.

**Comment by Emmanuel-obiora** [comment]
I have deleted the empty files.

**Review by DanSam5K — APPROVED** [review]
### Hi @Emmanuel-obiora , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
