### PR TITLE
tasks

### PR DESCRIPTION
**Pull request by MccGrey**
## all tasks complete

💻💻💻

### CODE REVIEW

**Comment by DanSam5K** [comment]
- Hi @MccGrey,
  - There seems to be conflict at the moment, kindly resolve if you can 🙏

**Comment by MccGrey** [comment]
alright boss 💻💻💻

**Comment by MccGrey** [comment]
conflicts resolved

**Review by DanSam5K — APPROVED** [review]
Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
